feat: sprint 14 db JPA implemented
unstablecookie/java-shareit pull request #3
Opened 2024-05-13 19:44 UTC by unstablecookie

sprint 14 main JPA features implemented

2024-05-14 14:26 UTC, TomattmanYandex requested changes
Привет, я оставил много комментариев в пакете букинга, и только там, потому что эти случаи будут везде повторяться, так что они относятся ко всему проекту, и поправить надо везде

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (addedBookingFull.isEmpty()) {
обычно это логика сервиса, сервис получает данные из базы, и если с нимим что-то не так кидает ошибку

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "not found");
а в тексте сообщения стоит указать что не найдено, тем более что не найдено, если мы добавляем обьект

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (bookingDtoFull.isEmpty()) {
про это я уже написал, в остальных местах где это встретится, не буду писать

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        Optional<List<BookingDtoFull>> bookings = bookingService.getOwnerBookings(userId);
вот тут вообще странно, зачем возвращать Optional вокруг списка если можно вернуть пустой список

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                            @RequestParam(required = true, defaultValue = "ALL") String state) {
в параметрах можно указать сразу что state это не строка а State enum

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                            @RequestParam(required = true, defaultValue = "ALL") String state) {
а еще как вместе уживаются required true и дефолтное значение? ведь если значения не будет, то метод не выполнится из-за первого, а как дефолтное значение проставится в уже имеющееся

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findUsersBookings(Long userId);
у jpa есть удобная штука
он умеет запросы строить по имени метода
например можно было просто сделать метод findByUserId(Long id) или findByUser(User user)

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findUsersBookings(Long userId);
но тут может быть чуть больше сложностей с join так как там по разному делаются доп запросы в базу, иногда с join иногда есть ленивая подгрузка и делаются доп запросы когда обращаемся к полю

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    Optional<BookingDtoFull> addBooking(BookingDto bookingDto, Long userId);
зачем тут везде Optional
он имеет смысл в репозитории, когда мы запрашиваем один обьект и он может быть не найден, 
а на уровне сервиса не имеет смысла, так как если что то не найдено, уже сервис может пробросить ошибку
еще причины может разберу в самом сервисе

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        Optional<User> booker = userRepository.findById(bookingDto.getBookerId());
эту штуку можно обработать проще
User booker = userRepository.findById(bookingDto.getBookerId()).orElseThrow(()-> new EntityNotFoundException(String.format("user id %d not found", bookingDto.getBookerId())));
orElseThrow пробросит ошибку, если optional пустой
и сделав таким образом
1) мы может просто проверить что существует пользователь, например в некоторых местах нам не нужен сам пользователь, нужна только проверка что он существует, и тогда можем даже в переменную не записывать, если пользователь не найден, то просто кинется ошибка 
2) нам не нужны доп проверки как в строке 41-43, и вызовы допольнительные get() как в строчке  51

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +            return Optional.empty();
зачем тут возвращать optional.empty если можно сразу прокинуть соответствующую ошибку и .... все

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +            return Optional.empty();
так, будет  ошибка что кто то не найден, но если пользователь не соответсвует, то это должна быть какая то другая ошибка

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +            return Optional.empty();
вот снова, тут бы ошибку сразу прокинуть

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        return Optional.of(BookingMapper.toBookingDtoFull(bookingRepository.save(booking)));
и снова, непонятно зачем оборачивать в optional

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        Set<Booking> bookings = items.stream()
Плохой подход, потому что если у пользователя 100 вещей, то будет 102 запроса в базу
Исправить можно несколькими способами
1) уменьшаем количество запросов до одного, делая сложный запрос с Join 
что то вроде select booking, join item by booking to item, join user by owner to user where userID = значению, и если пользователь не найден, то просто вернется пустой списко
2) два запроса - то же что и выше, но в начале проверяем наличие пользователя отдельным запросом
3) 3 запроса 
1 -> проверяем пользователя
2 -> получаем все его вещи
3 -> bookingRepository.findByItemIdInOrderByStartDesc
с частью In метод должен принимать список, и вернет все те значения которые пересекаются

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        if (queryStatus.equals(State.REJECTED) || queryStatus.equals(State.WAITING)) {
enum можно сравнивать и через ==

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +            Status status = Status.valueOf(queryStatus.name());
Не понял зачем?
насколько я понимаю, есть два перечисления  с одинаковыми значениями, но зачем нам тогда два нужны, почему не использовать один в разным местах?

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +                    .map(x -> bookingRepository.findByItemIdOrderByStartDesc(x.getId()))
про количество запросов я уже писал

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +            switch (queryStatus) {
почему нельзя было сделать без if?
тут if и switch case выполняют одинаковую работу, разное выполнение в зависимости от значения queryStatus, так зачем усложнаять?

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +                case ALL: bookings = items.stream()
было бы удобно, если бы содержимое блоков case было вынесено в приватные методы с понятными именами, и можно чтобы они сразу возвращали нужные объекты( сразу букингДто)
тогда читалось бы гораздо проще
case ALL: return getAllBokings(items);
case PAST: return getPastBookings(items);

в таком случае 
во первых метод становится читаемее, 
во вторых не нужны лишние break;
в третьих можно избежать дублировния кода

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +                        .filter(x -> x.getEnd().isBefore(LocalDateTime.now()))
вот эту фильтрацию можно включить в sql запрос
представь что у тебя есть популярный в будущем предмет предмет на него есть тысячи заказов на год вперед, а ты его добавил только вчера и предыдущий заказ только один, зачем для того чтобы показать прошлый заказы, делать запрос за всеми?

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +            throw new EntityNotFoundException("user is not an owner");
почему если не тот пользователь, то кидается NotFoundException?

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +            throw new EntityNotFoundException("user is not an owner");
А еще мы не проверили, что пользователь вообще существует

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/LastBookingDto.java
> +    Long id;
модификаторы доступа

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoFull.java
> +public class BookingDtoFull {
я бы назвал BookingFullDto чтобы часть Dto всегда ыбла в конце, и мы легко понимали что это Dto

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/NextBookingDto.java
> +    Long bookerId;
Модификаторы доступа, и чем вообще отличается от LastBookingDto?
почему бы не назвать BookingShortDto и использовать один класс в друх местах,
или (может быть не уместно по ребованиям или тестам, можно в ItemDto хранить две перменные BookingDto с именами nextBooking, lastBooking

2024-05-14 14:26 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Какой смысл сразу использовать 
DROP TABLE IF EXISTS users;
и 
CREATE TABLE IF NOT EXISTS users 

делаю предсказание, при создании таблицы users ее никогда существовать не будет

Стоит удалить удаление таблиц, ибо оно будет очищать базу каждый раз

2024-05-15 06:55 UTC, unstablecookie commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +            throw new EntityNotFoundException("user is not an owner");
исключение поменял, но тесты ожидают 404
"Status code is 404 | AssertionError: expected 400 to be one of [ 404 ]"
поэтому оставил NotFoundException

2024-05-16 10:41 UTC, TomattmanYandex approved these changes
Принято

2024-05-16 11:35 UTC, merged